= Pion

A Python 3 library for the http://amzn.github.io/ion-docs/[Ion format],
released under the LICENSE[MIT Licence].

image:https://travis-ci.org/tlocke/pion.svg?branch=master["Build Status",
link="https://travis-ci.org/tlocke/pion"]


== Installation

It's a good idea to set up a virtualenv:

 virtualenv venv
 source venv/bin/activate

then install Pion with pip:

 pip install pion


== Quickstart

To go from a Python object to an Ion string use `pion.dumps`. To go from an Ion
string to a Python object use `pion.loads`. Eg.

....
>>> from pion import loads, dumps
>>> from datetime import datetime, timezone
>>>
>>> # Take a Python object
>>> book = {
...     'title': 'A Hero of Our Time',
...     'read_date': datetime(2017, 7, 16, 14, 5, tzinfo=timezone.utc),
...     'would_recommend': True,
...     'description': None,
...     'number_of_novellas': 5,
...     'price': Decimal('7.99'),
...     'weight': 6.88}
>>>
>>> # Output it as an Ion string
>>> ion_str = dumps(book)
>>> print(ion_str)
>>>
>>> # Load the Ion string, to give us back the Python object
>>> loads(ion_str)

....


== Contributing

Useful links:

* https://amzn.github.io/ion-docs/spec.html[Ion Specification]
* http://www.antlr.org/api/Java/index.html?overview-summary.html[ANTLR JavaDocs]

To run the tests:

* Change to the `pion` directory: `cd pion`
* Create a virtual environment: `virtualenv --python=python3 venv`
* Active the virtual environment: `source venv/bin/activate`
* Install tox: `pip install tox`
* Run tox: `tox`

The core parser is created using https://github.com/antlr/antlr4[ANTLR] from
the http://amzn.github.io/ion-docs/grammar/IonText.g4.txt[Ion grammar]. To
create the parser files, go to the `antlr` directory and download the ANTLR jar
and then run the following command:

 java -jar antlr-4.7-complete.jar -Dlanguage=Python3 IonText.g4


=== Making A New Release

Run `tox` to make sure all tests pass, then update the `Release Notes` section
then do:

....
git tag -a x.y.z -m "version x.y.z"
python setup.py register sdist bdist_wheel upload --sign
....
